/* @pjs preload=
"bg/start1.png,
bg/start2.png,
bg/end1.png,
bg/end2.png,
  
music/hoshi.mp3,
music/Mail Coach.wav,
music/death.mp3",
music/paradise.mp3,
  
music/effect/intowater.mp3,
music/effect/4knife.wav,
music/effect/belt.mp3,
music/effect/5red.mp3,
music/effect/into13.mp3,
music/effect/13with5.mp3,
music/effect/5fall.mp3,
music/effect/tv1.mp3,
music/effect/4fall.mp3,
music/effect/4kill5.mp3,
music/effect/start.mp3,
music/effect/intowater.mp3,
 
bg/kitchen.png,
bg/livingroom.png,
bg/livingroom1.png,
bg/attention.png,
OPENING/summary.png,
tips/knife.png,

knife.png,

fivewin/red.png,
fivewin/red.png,
fivewin/red.png,
music/warusi.mp3,
music/sinyou.mp3,
music/dark.mp3,
music/akuma.mp3,
music/creepy.mp3,
music/syodai.mp3,
music/syodai.mp3,
ED.mp4"; */